// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0--rc1
// source: replicate.proto

package replicate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReplicateService_NotifyToCopy_FullMethodName = "/replicate.ReplicateService/NotifyToCopy"
	ReplicateService_CopyFile_FullMethodName     = "/replicate.ReplicateService/CopyFile"
	ReplicateService_ConfirmCopy_FullMethodName  = "/replicate.ReplicateService/ConfirmCopy"
)

// ReplicateServiceClient is the client API for ReplicateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicateServiceClient interface {
	NotifyToCopy(ctx context.Context, in *NotifyToCopyRequest, opts ...grpc.CallOption) (*NotifyToCopyResponse, error)
	CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CopyFileResponse], error)
	ConfirmCopy(ctx context.Context, in *ConfirmCopyRequest, opts ...grpc.CallOption) (*ConfirmCopyResponse, error)
}

type replicateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicateServiceClient(cc grpc.ClientConnInterface) ReplicateServiceClient {
	return &replicateServiceClient{cc}
}

func (c *replicateServiceClient) NotifyToCopy(ctx context.Context, in *NotifyToCopyRequest, opts ...grpc.CallOption) (*NotifyToCopyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyToCopyResponse)
	err := c.cc.Invoke(ctx, ReplicateService_NotifyToCopy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicateServiceClient) CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CopyFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReplicateService_ServiceDesc.Streams[0], ReplicateService_CopyFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyFileRequest, CopyFileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplicateService_CopyFileClient = grpc.ServerStreamingClient[CopyFileResponse]

func (c *replicateServiceClient) ConfirmCopy(ctx context.Context, in *ConfirmCopyRequest, opts ...grpc.CallOption) (*ConfirmCopyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmCopyResponse)
	err := c.cc.Invoke(ctx, ReplicateService_ConfirmCopy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicateServiceServer is the server API for ReplicateService service.
// All implementations must embed UnimplementedReplicateServiceServer
// for forward compatibility.
type ReplicateServiceServer interface {
	NotifyToCopy(context.Context, *NotifyToCopyRequest) (*NotifyToCopyResponse, error)
	CopyFile(*CopyFileRequest, grpc.ServerStreamingServer[CopyFileResponse]) error
	ConfirmCopy(context.Context, *ConfirmCopyRequest) (*ConfirmCopyResponse, error)
	mustEmbedUnimplementedReplicateServiceServer()
}

// UnimplementedReplicateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicateServiceServer struct{}

func (UnimplementedReplicateServiceServer) NotifyToCopy(context.Context, *NotifyToCopyRequest) (*NotifyToCopyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyToCopy not implemented")
}
func (UnimplementedReplicateServiceServer) CopyFile(*CopyFileRequest, grpc.ServerStreamingServer[CopyFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CopyFile not implemented")
}
func (UnimplementedReplicateServiceServer) ConfirmCopy(context.Context, *ConfirmCopyRequest) (*ConfirmCopyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmCopy not implemented")
}
func (UnimplementedReplicateServiceServer) mustEmbedUnimplementedReplicateServiceServer() {}
func (UnimplementedReplicateServiceServer) testEmbeddedByValue()                          {}

// UnsafeReplicateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicateServiceServer will
// result in compilation errors.
type UnsafeReplicateServiceServer interface {
	mustEmbedUnimplementedReplicateServiceServer()
}

func RegisterReplicateServiceServer(s grpc.ServiceRegistrar, srv ReplicateServiceServer) {
	// If the following call pancis, it indicates UnimplementedReplicateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplicateService_ServiceDesc, srv)
}

func _ReplicateService_NotifyToCopy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyToCopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicateServiceServer).NotifyToCopy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicateService_NotifyToCopy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicateServiceServer).NotifyToCopy(ctx, req.(*NotifyToCopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicateService_CopyFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CopyFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicateServiceServer).CopyFile(m, &grpc.GenericServerStream[CopyFileRequest, CopyFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplicateService_CopyFileServer = grpc.ServerStreamingServer[CopyFileResponse]

func _ReplicateService_ConfirmCopy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmCopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicateServiceServer).ConfirmCopy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicateService_ConfirmCopy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicateServiceServer).ConfirmCopy(ctx, req.(*ConfirmCopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicateService_ServiceDesc is the grpc.ServiceDesc for ReplicateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replicate.ReplicateService",
	HandlerType: (*ReplicateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyToCopy",
			Handler:    _ReplicateService_NotifyToCopy_Handler,
		},
		{
			MethodName: "ConfirmCopy",
			Handler:    _ReplicateService_ConfirmCopy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CopyFile",
			Handler:       _ReplicateService_CopyFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "replicate.proto",
}
