// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0--rc1
// source: download.proto

package download

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DownloadService_RequestDownloadInfo_FullMethodName = "/download.DownloadService/RequestDownloadInfo"
	DownloadService_DownloadChunk_FullMethodName       = "/download.DownloadService/DownloadChunk"
)

// DownloadServiceClient is the client API for DownloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DownloadServiceClient interface {
	RequestDownloadInfo(ctx context.Context, in *MasterDownloadRequest, opts ...grpc.CallOption) (*MasterDownloadResponse, error)
	DownloadChunk(ctx context.Context, in *ChunkDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChunkDownloadResponse], error)
}

type downloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDownloadServiceClient(cc grpc.ClientConnInterface) DownloadServiceClient {
	return &downloadServiceClient{cc}
}

func (c *downloadServiceClient) RequestDownloadInfo(ctx context.Context, in *MasterDownloadRequest, opts ...grpc.CallOption) (*MasterDownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MasterDownloadResponse)
	err := c.cc.Invoke(ctx, DownloadService_RequestDownloadInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadServiceClient) DownloadChunk(ctx context.Context, in *ChunkDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChunkDownloadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DownloadService_ServiceDesc.Streams[0], DownloadService_DownloadChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChunkDownloadRequest, ChunkDownloadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DownloadService_DownloadChunkClient = grpc.ServerStreamingClient[ChunkDownloadResponse]

// DownloadServiceServer is the server API for DownloadService service.
// All implementations must embed UnimplementedDownloadServiceServer
// for forward compatibility.
type DownloadServiceServer interface {
	RequestDownloadInfo(context.Context, *MasterDownloadRequest) (*MasterDownloadResponse, error)
	DownloadChunk(*ChunkDownloadRequest, grpc.ServerStreamingServer[ChunkDownloadResponse]) error
	mustEmbedUnimplementedDownloadServiceServer()
}

// UnimplementedDownloadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDownloadServiceServer struct{}

func (UnimplementedDownloadServiceServer) RequestDownloadInfo(context.Context, *MasterDownloadRequest) (*MasterDownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDownloadInfo not implemented")
}
func (UnimplementedDownloadServiceServer) DownloadChunk(*ChunkDownloadRequest, grpc.ServerStreamingServer[ChunkDownloadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadChunk not implemented")
}
func (UnimplementedDownloadServiceServer) mustEmbedUnimplementedDownloadServiceServer() {}
func (UnimplementedDownloadServiceServer) testEmbeddedByValue()                         {}

// UnsafeDownloadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DownloadServiceServer will
// result in compilation errors.
type UnsafeDownloadServiceServer interface {
	mustEmbedUnimplementedDownloadServiceServer()
}

func RegisterDownloadServiceServer(s grpc.ServiceRegistrar, srv DownloadServiceServer) {
	// If the following call pancis, it indicates UnimplementedDownloadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DownloadService_ServiceDesc, srv)
}

func _DownloadService_RequestDownloadInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasterDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).RequestDownloadInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadService_RequestDownloadInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).RequestDownloadInfo(ctx, req.(*MasterDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadService_DownloadChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChunkDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DownloadServiceServer).DownloadChunk(m, &grpc.GenericServerStream[ChunkDownloadRequest, ChunkDownloadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DownloadService_DownloadChunkServer = grpc.ServerStreamingServer[ChunkDownloadResponse]

// DownloadService_ServiceDesc is the grpc.ServiceDesc for DownloadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DownloadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "download.DownloadService",
	HandlerType: (*DownloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestDownloadInfo",
			Handler:    _DownloadService_RequestDownloadInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadChunk",
			Handler:       _DownloadService_DownloadChunk_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "download.proto",
}
